name: Automation Test Run

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from branch
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.0"

    - name: Upgrade & Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt

    - name: Playwright Install
      run: python -m playwright install --with-deps

    - name: Run Tests
      env:
        OASIS_BASE_URL: ${{ secrets.OASIS_BASE_URL }}
        OASIS_LOGIN_URL: ${{ secrets.OASIS_LOGIN_URL }}
        GUEST_EMAIL: ${{ secrets.GUEST_EMAIL }}
        HOST_EMAIL: ${{ secrets.HOST_EMAIL }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        CORRECT_PASSWORD: ${{ secrets.CORRECT_PASSWORD }}
        INCORRECT_PASSWORD: ${{ secrets.INCORRECT_PASSWORD }}
      run: pytest -m regression

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30
